name: CI

on: push

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:stable
    steps:
    - uses: actions/checkout@v2
    - run:  find . -type f -name '*.sh' | xargs shellcheck --external-sources -e 2016
